# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "errors"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true  
s3_bucket = "my-sam-deployments-bucket111"  
s3_prefix = "errors"
region = "us-east-1"
disable_rollback = true  
parameter_overrides = "MongoUriParameter=\"\" DbNameParameter=\"ERRORS\" CollectionNameParameter=\"error_logs\""
image_repositories = []

[default.package.parameters]
resolve_s3 = false  

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
