name: Basic Syntax Check

on:
  push:
    branches:
      - backend 

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  

    - name: Set up Node.js
      uses: actions/setup-node@v3  
      with:
        node-version: '18'  

    - name: Install dependencies
      run: npm install

    - name: Set up environment variables
      run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
    - name: Run basic syntax check
      run: |
        for file in $(find . -type f -name "*.js"  ! -path "./node_modules/*"); do
          node --check "$file" || exit 1
        done

    - name: Run tests
      run: npm test