name: Basic Syntax Check

on:
  push:
    branches:
      - backend 

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  

    - name: Set up Node.js
      uses: actions/setup-node@v3  
      with:
        node-version: '18'  

    - name: Install dependencies
      run: npm install
    - name: Debug MONGO_URI
      run: echo "MONGO_URI=${{ secrets.MONGO_URI }}"
      env:
       MONGO_URI: ${{ secrets.MONGO_URI }}
    - name: Set up environment variables
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: echo "Environment variables set."
    - name: Run basic syntax check
      run: |
        for file in $(find . -type f -name "*.js"  ! -path "./node_modules/*"); do
          node --check "$file" || exit 1
        done

    - name: Run tests
      env:
       MONGO_URI: ${{ secrets.MONGO_URI }}
      run: npm test